db:
     image: mysql/mysql-server:5.7
     ports:
       - "3306:3306"
     environment:
       - "MYSQL_ROOT_PASSWORD=passe"
       - "MYSQL_USER=your_user"
       - "MYSQL_PASSWORD=passe"
       - "MYSQL_DATABASE=db"
webtest:
     build: ./
     ports:
       - "8010:80"
     links:
       - "db:db"
     working_dir: "/home/docker"
